"""added book

Revision ID: 01d85a2b5c36
Revises: 697a1ad43a6c
Create Date: 2023-10-03 09:35:47.897197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01d85a2b5c36'
down_revision = '697a1ad43a6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
