"""review

Revision ID: 697a1ad43a6c
Revises: 4b66f4cbdc83
Create Date: 2023-10-03 09:28:50.685125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '697a1ad43a6c'
down_revision = '4b66f4cbdc83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
